/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/9.2.1/userguide/multi_project_builds.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "RuneTale"

include(":platform:testing-core")
include(":platform:testing-ecs")
include(":platform:testing-junit")
include(":plugins:skills")
include(":plugins:skills-api")
include(":plugins:skills-gathering")
include(":plugins:skills-crafting")
include(":plugins:skills-equipment")
include(":plugins:skills-combat")
include(":plugins:skills-actions")
include(":plugins:block-regeneration")
